07-24 15:47:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "TULLY" не найден
Column "TULLY" not found; SQL statement:
select * from users where user_name=tully [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:180)
	at org.h2.command.dml.Select.prepare(Select.java:880)
	at org.h2.command.Parser.prepareCommand(Parser.java:247)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execQuery(Executor.java:27)
	at dbService.dao.UsersDAO.getUserId(UsersDAO.java:25)
	at dbService.DBService.addUser(DBService.java:28)
	at main.Main.main(Main.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
04-03 12:08:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "USER_NAME" не найден
Column "USER_NAME" not found; SQL statement:
insert into users (user_name) values ('tully', 'll') [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:648)
	at org.h2.command.Parser.parseColumn(Parser.java:856)
	at org.h2.command.Parser.parseColumnList(Parser.java:840)
	at org.h2.command.Parser.parseInsert(Parser.java:1040)
	at org.h2.command.Parser.parsePrepared(Parser.java:401)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execUpdate(Executor.java:24)
	at dbService.dao.UsersDAO.insertUser(UsersDAO.java:39)
	at dbService.DBService.addUser(DBService.java:38)
	at main.Main.main(Main.java:30)
04-03 12:11:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USERS (LOGIN) VALUES ('tully')
 INSERT[*] INTO USERS (PASS) VALUES ('ll') "
Syntax error in SQL statement "INSERT INTO USERS (LOGIN) VALUES ('tully')
 INSERT[*] INTO USERS (PASS) VALUES ('ll') "; SQL statement:
insert into users (login) values ('tully')
 insert into users (pass) values ('ll') [42000-187]
04-03 12:13:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неверное количество столбцов
Column count does not match; SQL statement:
insert into users values ('tully', 'll') [21002-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:247)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execUpdate(Executor.java:24)
	at dbService.dao.UsersDAO.insertUser(UsersDAO.java:39)
	at dbService.DBService.addUser(DBService.java:38)
	at main.Main.main(Main.java:30)
04-03 12:21:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "USER_NAME" не найден
Column "USER_NAME" not found; SQL statement:
select * from users where user_name='tully' [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:178)
	at org.h2.command.dml.Select.prepare(Select.java:880)
	at org.h2.command.Parser.prepareCommand(Parser.java:247)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execQuery(Executor.java:32)
	at dbService.dao.UsersDAO.getUserId(UsersDAO.java:32)
	at dbService.DBService.addUser(DBService.java:40)
	at main.Main.main(Main.java:30)
04-03 12:22:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "tully"
Data conversion error converting "tully"; SQL statement:
select * from users where id='tully' [22018-187]
